from __future__ import annotations

from collections.abc import AsyncIterator

from app.core.config import settings
from app.core.types import Message, ProviderName, Role
from app.orchestrator.compare import COMPARE_PROVIDERS, stream_compare
from app.orchestrator.provider_stream import stream_provider_events
from app.prompts.templates import SUPERMIND_SCRIBE, SUPERMIND_SYNTHESIS


def _format_individual_answers(answers: dict[ProviderName, str]) -> str:
    return "\n\n".join(
        f"{provider.value}:\n{content or '[no answer]'}"
        for provider, content in answers.items()
    )


def _excerpt(content: str, limit: int = 1600) -> str:
    text = content.strip()
    if len(text) <= limit:
        return text
    return f"{text[:limit].rstrip()}..."


def _fallback_unified_response(prompt: str, answers: dict[ProviderName, str]) -> str:
    blocks = [
        "Unified response could not be generated by the synthesis provider, so this is a best-effort compiled response from the completed individual model answers.",
        "",
        f"Original request: {prompt}",
        "",
        "## Best Available Combined Answer",
    ]

    completed = [(provider, content) for provider, content in answers.items() if content.strip()]
    if not completed:
        blocks.append("- No individual model answer completed successfully.")
        return "\n".join(blocks)

    longest_provider, longest_answer = max(completed, key=lambda item: len(item[1]))
    blocks.extend(
        [
            f"The most complete individual answer came from {longest_provider.value}. Use it as the primary draft, then review the other individual answers for alternatives and missing details.",
            "",
            _excerpt(longest_answer, 2200),
            "",
            "## Individual Answer Excerpts",
        ]
    )

    for provider, content in completed:
        if provider == longest_provider:
            continue
        blocks.extend(
            [
                "",
                f"### {provider.value}",
                _excerpt(content),
            ]
        )

    return "\n".join(blocks)


def _fallback_scribe_notes(prompt: str, answers: dict[ProviderName, str], unified: str) -> str:
    completed = [provider.value for provider, content in answers.items() if content.strip()]
    return "\n".join(
        [
            "## Decision Brief",
            f"- Request: {prompt}",
            "- Automated Scribe generation could not use the synthesis provider, so these notes were created from saved Super Mind outputs.",
            "",
            "## Consensus",
            f"- Completed individual responses: {', '.join(completed) if completed else 'none'}.",
            "- Review the Unified fallback and Individual tabs together before making a decision.",
            "",
            "## Disagreements / Uncertainty",
            "- Not automatically extracted because the Scribe provider failed or quota was exhausted.",
            "",
            "## Risks",
            "- The unified response is a fallback compiled from individual answers, not a fresh model synthesis.",
            "",
            "## Open Questions",
            "- Which individual answer is most aligned with the user's actual constraints?",
            "- Are provider credits/quotas restored for a full synthesis rerun?",
            "",
            "## Next Actions",
            "- Read the Unified fallback.",
            "- Check Individual responses for missing ideas.",
            "- Rerun Super Mind after Anthropic/OpenAI/Gemini quota issues are fixed.",
            "",
            "## Unified Fallback Excerpt",
            _excerpt(unified, 1200),
        ]
    )


async def stream_supermind(
    prompt: str,
    premium: bool = False,
) -> AsyncIterator[dict[str, object]]:
    messages = [Message(role=Role.USER, content=prompt)]
    answers: dict[ProviderName, str] = {}
    collected: dict[ProviderName, list[str]] = {}

    yield {"type": "round_start", "round": 1}
    async for event in stream_compare(messages, premium, COMPARE_PROVIDERS, round_number=1):
        event_type = str(event["type"])
        if event_type == "delta":
            provider = ProviderName(str(event["provider"]))
            collected.setdefault(provider, []).append(str(event["delta"]))
        elif event_type == "provider_done":
            provider = ProviderName(str(event["provider"]))
            answers[provider] = "".join(collected.get(provider, []))
        elif event_type == "error":
            provider = ProviderName(str(event["provider"]))
            answers[provider] = f"[error] {event.get('message', 'Provider failed.')}"

        yield event
    yield {"type": "round_done", "round": 1}

    synthesis_provider = ProviderName(settings.synthesis_provider)
    synthesis_round = 2
    synthesis_messages = [
        Message(
            Role.SYSTEM,
            SUPERMIND_SYNTHESIS.format(answers=_format_individual_answers(answers)),
        ),
        Message(Role.USER, prompt),
    ]
    synthesis_content: list[str] = []
    synthesis_failed = False
    synthesis_error = ""

    yield {
        "type": "synthesis_start",
        "provider": synthesis_provider.value,
        "round": synthesis_round,
    }

    async for event in stream_provider_events(
        synthesis_provider,
        synthesis_messages,
        premium,
        synthesis_round,
    ):
        if event["type"] == "delta":
            delta = str(event["delta"])
            synthesis_content.append(delta)
            yield {
                "type": "synthesis_delta",
                "provider": event["provider"],
                "round": synthesis_round,
                "delta": delta,
                **(
                    {"fallback_provider": event["fallback_provider"]}
                    if "fallback_provider" in event
                    else {}
                ),
            }
        elif event["type"] == "provider_done":
            continue
        elif event["type"] == "error":
            synthesis_failed = True
            synthesis_error = str(event.get("message", "Synthesis provider failed."))
        else:
            yield event

    if synthesis_failed or not "".join(synthesis_content).strip():
        fallback = _fallback_unified_response(prompt, answers)
        synthesis_content = [fallback]
        yield {
            "type": "synthesis_delta",
            "provider": synthesis_provider.value,
            "round": synthesis_round,
            "delta": fallback,
            "fallback_reason": synthesis_error or "Synthesis provider returned no content.",
        }

    yield {
        "type": "synthesis_done",
        "provider": synthesis_provider.value,
        "round": synthesis_round,
        "content": "".join(synthesis_content),
    }

    scribe_round = 3
    scribe_content: list[str] = []
    scribe_messages = [
        Message(
            Role.SYSTEM,
            SUPERMIND_SCRIBE.format(
                prompt=prompt,
                answers=_format_individual_answers(answers),
                unified="".join(synthesis_content),
            ),
        ),
        Message(Role.USER, "Write the scribe notes now."),
    ]

    yield {
        "type": "scribe_start",
        "provider": synthesis_provider.value,
        "round": scribe_round,
    }

    scribe_failed = False
    scribe_error = ""
    async for event in stream_provider_events(
        synthesis_provider,
        scribe_messages,
        premium,
        scribe_round,
    ):
        if event["type"] == "delta":
            delta = str(event["delta"])
            scribe_content.append(delta)
            yield {
                "type": "scribe_delta",
                "provider": event["provider"],
                "round": scribe_round,
                "delta": delta,
                **(
                    {"fallback_provider": event["fallback_provider"]}
                    if "fallback_provider" in event
                    else {}
                ),
            }
        elif event["type"] == "provider_done":
            continue
        elif event["type"] == "error":
            scribe_failed = True
            scribe_error = str(event.get("message", "Scribe provider failed."))
        else:
            yield event

    if scribe_failed or not "".join(scribe_content).strip():
        fallback = _fallback_scribe_notes(
            prompt,
            answers,
            "".join(synthesis_content),
        )
        scribe_content = [fallback]
        yield {
            "type": "scribe_delta",
            "provider": synthesis_provider.value,
            "round": scribe_round,
            "delta": fallback,
            "fallback_reason": scribe_error or "Scribe provider returned no content.",
        }

    yield {
        "type": "scribe_done",
        "provider": synthesis_provider.value,
        "round": scribe_round,
        "content": "".join(scribe_content),
    }
